<?php

/*
 * This file is part of the Osirisgate package.
 *
 * (c) Ulrich Geraud AHOGLA <developer@osirisgate.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Osirisgate\Component\Lemonsqueezy\Model\Customer;

use Osirisgate\Component\Lemonsqueezy\Model\Trait\CreatedAtTrait;
use Osirisgate\Component\Lemonsqueezy\Model\Trait\UpdatedAtTrait;

/**
 * CustomerAttributes – LemonSqueezy API customer attributes model.
 *
 * Represents the attributes of a Customer entity in the LemonSqueezy API.
 * This class encapsulates customer-specific data such as store ID, name, email,
 * status, location details, revenue, subscription metrics, URLs, and test mode.
 *
 * @author Ulrich Geraud AHOGLA <developer@osirisgate.com>
 */
final class CustomerAttributes
{
    use CreatedAtTrait;
    use UpdatedAtTrait;

    /**
     * The ID of the store the customer belongs to.
     */
    private ?int $storeId = null;

    /**
     * The full name of the customer.
     */
    private ?string $name = null;

    /**
     * The email address of the customer.
     */
    private ?string $email = null;

    /**
     * The current status of the customer (e.g., 'active').
     */
    private ?string $status = null;

    /**
     * The city of the customer, if available.
     */
    private ?string $city = null;

    /**
     * The region or state of the customer, if available.
     */
    private ?string $region = null;

    /**
     * The country code of the customer (e.g., 'US', 'FR').
     */
    private ?string $country = null;

    /**
     * The total revenue generated by this customer in the store's currency (in cents or the smallest currency unit).
     */
    private ?int $totalRevenueCurrency = null;

    /**
     * The monthly recurring revenue (MRR) for this customer (in cents or the smallest currency unit).
     */
    private ?int $mrr = null;

    /**
     * The formatted status of the customer for display (e.g., 'Active').
     */
    private ?string $statusFormatted = null;

    /**
     * The formatted country name of the customer for display (e.g., 'United States', 'France').
     */
    private ?string $countryFormatted = null;

    /**
     * The formatted total revenue generated by this customer in the store's currency (e.g., '$100.00', '€100,00').
     */
    private ?string $totalRevenueCurrencyFormatted = null;

    /**
     * The formatted monthly recurring revenue (MRR) for this customer (e.g., '$10.00/month', '€10,00/mois').
     */
    private ?string $mrrFormatted = null;

    /**
     * An array of URLs related to the customer (e.g., 'customer_url').
     *
     * @var array<string, mixed>
     */
    private array $urls = [];

    /**
     * Indicates whether the customer was created in test mode.
     */
    private ?bool $testMode = null;

    /**
     * Returns the ID of the store the customer belongs to.
     *
     * @return int|null The store ID, or null if not set.
     */
    public function getStoreId(): ?int
    {
        return $this->storeId;
    }

    /**
     * Returns the name of the customer.
     *
     * @return string|null The customer's name, or null if not set.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Returns the email address of the customer.
     *
     * @return string|null The customer's email, or null if not set.
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Returns the current status of the customer.
     *
     * @return string|null The customer's status, or null if not set.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Returns the city of the customer.
     *
     * @return string|null The customer's city, or null if not set.
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * Returns the region or state of the customer.
     *
     * @return string|null The customer's region, or null if not set.
     */
    public function getRegion(): ?string
    {
        return $this->region;
    }

    /**
     * Returns the country code of the customer.
     *
     * @return string|null The customer's country code, or null if not set.
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Returns the total revenue generated by the customer in the store's currency.
     *
     * @return int|null The total revenue in cents, or null if not set.
     */
    public function getTotalRevenueCurrency(): ?int
    {
        return $this->totalRevenueCurrency;
    }

    /**
     * Returns the monthly recurring revenue (MRR) for the customer.
     *
     * @return int|null The MRR in cents, or null if not set.
     */
    public function getMrr(): ?int
    {
        return $this->mrr;
    }

    /**
     * Returns the formatted status of the customer.
     *
     * @return string|null The formatted status, or null if not set.
     */
    public function getStatusFormatted(): ?string
    {
        return $this->statusFormatted;
    }

    /**
     * Returns the formatted country name of the customer.
     *
     * @return string|null The formatted country, or null if not set.
     */
    public function getCountryFormatted(): ?string
    {
        return $this->countryFormatted;
    }

    /**
     * Returns the formatted total revenue generated by the customer in the store's currency.
     *
     * @return string|null The formatted total revenue, or null if not set.
     */
    public function getTotalRevenueCurrencyFormatted(): ?string
    {
        return $this->totalRevenueCurrencyFormatted;
    }

    /**
     * Returns the formatted monthly recurring revenue (MRR) for the customer.
     *
     * @return string|null The formatted MRR, or null if not set.
     */
    public function getMrrFormatted(): ?string
    {
        return $this->mrrFormatted;
    }

    /**
     * Returns the array of URLs related to the customer.
     *
     * @return array<string, mixed> An array of URLs.
     */
    public function getUrls(): array
    {
        return $this->urls;
    }

    /**
     * Returns whether the customer was created in test mode.
     *
     * @return bool|null True if in test mode, false otherwise, or null if not set.
     */
    public function isTestMode(): ?bool
    {
        return $this->testMode;
    }
}
