services:
  osirisgate.lemonsqueezy.php:
    build:
      context: .
      dockerfile: Dockerfile
    image: osirisgate.lemonsqueezy.php:latest
    container_name: osirisgate.lemonsqueezy.php
    restart: unless-stopped
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - "./:/var/www/html"
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    networks:
      - osirisgate

networks:
  osirisgate:
    driver: bridge
