<?php

/*
 * This file is part of the Osirisgate package.
 *
 * (c) Ulrich Geraud AHOGLA <developer@osirisgate.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Osirisgate\Component\Lemonsqueezy\Model\Store;

use Osirisgate\Component\Lemonsqueezy\Model\Trait\CreatedAtTrait;
use Osirisgate\Component\Lemonsqueezy\Model\Trait\UpdatedAtTrait;

/**
 * StoreAttributes – LemonSqueezy API store attributes model.
 *
 * Represents the detailed properties of a store as retrieved from the
 * LemonSqueezy API. This class encapsulates various metadata associated
 * with a store, including its name, a unique slug, the store's domain,
 * its primary URL, the URL of its avatar image, the current subscription
 * plan the store is on, the country code and the full name of the country
 * where the store is based, the store's default currency, and key sales
 * and revenue statistics such as total sales, total revenue, sales in the
 * last 30 days, and revenue in the last 30 days.
 *
 * The class utilizes traits for managing timestamp-related attributes
 * (created at and updated at).
 *
 * @author Ulrich Geraud AHOGLA <developer@osirisgate.com>
 */
final class StoreAttributes
{
    use CreatedAtTrait;
    use UpdatedAtTrait;

    /**
     * @var string|null The name of the store.
     */
    private ?string $name = null;

    /**
     * @var string|null A unique, human-readable identifier for the store.
     */
    private ?string $slug = null;

    /**
     * @var string|null The primary domain of the store.
     */
    private ?string $domain = null;

    /**
     * @var string|null The main URL of the store.
     */
    private ?string $url = null;

    /**
     * @var string|null The URL of the store's avatar or logo.
     */
    private ?string $avatarUrl = null;

    /**
     * @var string|null The current subscription plan of the store.
     */
    private ?string $plan = null;

    /**
     * @var string|null The two-letter country code of the store (ISO 3166-1 alpha-2).
     */
    private ?string $country = null;

    /**
     * @var string|null The full, human-readable name of the store's country.
     */
    private ?string $countryNicename = null;

    /**
     * @var string|null The default currency code of the store (ISO 4217).
     */
    private ?string $currency = null;

    /**
     * @var int|null The total number of sales processed by the store.
     */
    private ?int $totalSales = null;

    /**
     * @var int|null The total revenue generated by the store (in the store's currency unit).
     */
    private ?int $totalRevenue = null;

    /**
     * @var int|null The number of sales in the last 30 days.
     */
    private ?int $thirtyDaySales = null;

    /**
     * @var int|null The revenue generated in the last 30 days (in the store's currency unit).
     */
    private ?int $thirtyDayRevenue = null;

    /**
     * Returns the name of the store.
     *
     * @return string|null The store name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Returns the unique slug of the store.
     *
     * @return string|null The store slug.
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * Returns the primary domain of the store.
     *
     * @return string|null The store domain.
     */
    public function getDomain(): ?string
    {
        return $this->domain;
    }

    /**
     * Returns the main URL of the store.
     *
     * @return string|null The store URL.
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Returns the URL of the store's avatar or logo.
     *
     * @return string|null The avatar URL.
     */
    public function getAvatarUrl(): ?string
    {
        return $this->avatarUrl;
    }

    /**
     * Returns the current subscription plan of the store.
     *
     * @return string|null The store's plan.
     */
    public function getPlan(): ?string
    {
        return $this->plan;
    }

    /**
     * Returns the two-letter country code of the store.
     *
     * @return string|null The country code.
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Returns the full name of the store's country.
     *
     * @return string|null The country name.
     */
    public function getCountryNicename(): ?string
    {
        return $this->countryNicename;
    }

    /**
     * Returns the default currency code of the store.
     *
     * @return string|null The currency code.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Returns the total number of sales processed by the store.
     *
     * @return int|null The total sales count.
     */
    public function getTotalSales(): ?int
    {
        return $this->totalSales;
    }

    /**
     * Returns the total revenue generated by the store.
     *
     * @return int|null The total revenue amount.
     */
    public function getTotalRevenue(): ?int
    {
        return $this->totalRevenue;
    }

    /**
     * Returns the number of sales in the last 30 days.
     *
     * @return int|null The 30-day sales count.
     */
    public function getThirtyDaySales(): ?int
    {
        return $this->thirtyDaySales;
    }

    /**
     * Returns the revenue generated in the last 30 days.
     *
     * @return int|null The 30-day revenue amount.
     */
    public function getThirtyDayRevenue(): ?int
    {
        return $this->thirtyDayRevenue;
    }
}
